# ------------------------------ Model registry ------------------------------

MODEL_REGISTRY = {
    # Minimal, fast
    "schnell": {
        "endpoint": "fal-ai/flux/schnell",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/flux/schnell/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "image_size": {
                "type": "whi",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd","square","portrait_4_3","portrait_16_9","landscape_4_3","landscape_16_9",],
                "flags": ["-i", "--image-size"],
            },
            "width": {
                "type": int,
                "default": None,
                "help": "image width in pixels (requires --height)",
                "flags": ["-w", "--width"],
            },
            "height": {
                "type": int,
                "default": None,
                "help": "image height in pixels (requires --width)",
                "flags": ["-h", "--height"],
            },
            "num_inference_steps": {
                "type": int,
                "default": 4,
                "help": "number of diffusion steps",
            },
            "guidance_scale": {
                "type": float,
                "default": 3.5,
                "help": "guidance scale",
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "disable the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
            "output_format": {
                "type": str,
                "default": "jpeg",
                "help": "output image format",
            },
            "acceleration": {
                "type": str,
                "default": "none",
                "help": "acceleration preset",
            },
        },
    },
    # HiDream fast text-to-image model
    "hidream-fast": {
        "endpoint": "fal-ai/hidream-i1-fast",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/hidream-i1-fast/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "negative_prompt": {
                "type": str,
                "default": "",
                "help": "negative prompt to steer away from unwanted details",
                "flags": ["-n", "--negative-prompt"],
            },
            "image_size": {
                "type": "whi",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd","square","portrait_4_3","portrait_16_9","landscape_4_3","landscape_16_9",],
                "flags": ["-i", "--image-size"],
            },
            "width": {
                "type": int,
                "default": None,
                "help": "image width in pixels (requires --height)",
                "flags": ["-w", "--width"],
            },
            "height": {
                "type": int,
                "default": None,
                "help": "image height in pixels (requires --width)",
                "flags": ["-h", "--height"],
            },
            "num_inference_steps": {
                "type": int,
                "default": 16,
                "help": "number of diffusion steps",
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "skip the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
            "output_format": {
                "type": str,
                "default": "jpeg",
                "help": "output image format (jpeg, png)",
            },
        },
    },
    # HiDream dev text-to-image model
    "hidream-dev": {
        "endpoint": "fal-ai/hidream-i1-dev",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/hidream-i1-dev/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "negative_prompt": {
                "type": str,
                "default": "",
                "help": "negative prompt to steer away from unwanted details",
                "flags": ["-n", "--negative-prompt"],
            },
            "image_size": {
                "type": "whi",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd","square","portrait_4_3","portrait_16_9","landscape_4_3","landscape_16_9",],
                "flags": ["-i", "--image-size"],
            },
            "width": {
                "type": int,
                "default": None,
                "help": "image width in pixels (requires --height)",
                "flags": ["-w", "--width"],
            },
            "height": {
                "type": int,
                "default": None,
                "help": "image height in pixels (requires --width)",
                "flags": ["-h", "--height"],
            },
            "num_inference_steps": {
                "type": int,
                "default": 28,
                "help": "number of diffusion steps",
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "skip the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
            "output_format": {
                "type": str,
                "default": "jpeg",
                "help": "output image format (jpeg, png)",
            },
        },
    },
    # HiDream full text-to-image model
    "hidream-full": {
        "endpoint": "fal-ai/hidream-i1-full",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/hidream-i1-full/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "negative_prompt": {
                "type": str,
                "default": "",
                "help": "negative prompt to steer away from unwanted details",
                "flags": ["-n", "--negative-prompt"],
            },
            "image_size": {
                "type": "whi",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd","square","portrait_4_3","portrait_16_9","landscape_4_3","landscape_16_9",],
                "flags": ["-i", "--image-size"],
            },
            "width": {
                "type": int,
                "default": None,
                "help": "image width in pixels (requires --height)",
                "flags": ["-w", "--width"],
            },
            "height": {
                "type": int,
                "default": None,
                "help": "image height in pixels (requires --width)",
                "flags": ["-h", "--height"],
            },
            "num_inference_steps": {
                "type": int,
                "default": 50,
                "help": "number of diffusion steps",
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "skip the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
            "loras": {
                "type": str,
                "default": None,
                "help": "comma-separated list of LoRA identifiers (repeatable)",
                "flags": ["--loras"],
                "action": "append",
            },
            "output_format": {
                "type": str,
                "default": "jpeg",
                "help": "output image format (jpeg, png)",
            },
        },
    },
    # Dev model supports steps + guidance
    "dev": {
        "endpoint": "fal-ai/flux/dev",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/flux/dev/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "image_size": {
                "type": "whi",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd","square","portrait_4_3","portrait_16_9","landscape_4_3","landscape_16_9",],
                "flags": ["-i", "--image-size"],
            },
            "width": {
                "type": int,
                "default": None,
                "help": "image width in pixels (requires --height)",
                "flags": ["-w", "--width"],
            },
            "height": {
                "type": int,
                "default": None,
                "help": "image height in pixels (requires --width)",
                "flags": ["-h", "--height"],
            },
            "num_inference_steps": {
                "type": int,
                "default": 28,
                "help": "number of diffusion steps",
            },
            "guidance_scale": {
                "type": float,
                "default": 3.5,
                "help": "guidance scale",
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "disable the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
        },
    },
    # Realism model adds strength and output_format
    "realism": {
        "endpoint": "fal-ai/flux-realism",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/flux-realism/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "image_size": {
                "type": "i",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd","square","portrait_4_3","portrait_16_9","landscape_4_3","landscape_16_9",],
                "flags": ["-i", "--image-size"],
            },
            "strength": {
                "type": float,
                "default": 1.0,
                "help": "image-to-image strength",
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "output_format": {
                "type": str,
                "default": "jpeg",
                "help": "output image format",
            },
            "num_inference_steps": {
                "type": int,
                "default": 28,
                "help": "number of diffusion steps",
            },
            "guidance_scale": {
                "type": float,
                "default": 3.5,
                "help": "guidance scale",
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "disable the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
        },
    },
    # Nano Banana Gemini-enabled model
    "nano-banana": {
        "endpoint": "fal-ai/nano-banana",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/nano-banana/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "output_format": {
                "type": str,
                "default": "jpeg",
                "help": "output image format (jpeg, png, webp)",
            },
            "image_size": {
                "type": str,
                "type": "i",
                "allowed_sizes": ["21:9", "16:9", "3:2", "4:3", "5:4", "1:1", "4:5", "3:4", "2:3", "9:16", ],
                "default": "1:1",
                "help": "aspect ratio preset",
                "flags": ["-i", "--image-size"],
            },
        },
    },
    # Workflow with LoRA support
    "krea-lora": {
        "endpoint": "fal-ai/flux-krea-lora",
        "call": "run",
        "doc_url": "https://fal.ai/models/fal-ai/flux-krea-lora/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "image_size": {
                "type": "whi",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd","square","portrait_4_3","portrait_16_9","landscape_4_3","landscape_16_9",],
                "flags": ["-i", "--image-size"],
            },
            "width": {
                "type": int,
                "default": 1920,
                "help": "image width in px",
            },
            "height": {
                "type": int,
                "default": 1080,
                "help": "image height in px",
            },
            "loras": {
                "type": str,
                "default": None,
                "help": "comma-separated list of LoRA identifiers (repeatable)",
                "flags": ["--loras"],
                "action": "append",
            },
            "num_inference_steps": {
                "type": int,
                "default": 28,
                "help": "number of diffusion steps",
            },
            "guidance_scale": {
                "type": float,
                "default": 3.5,
                "help": "guidance scale",
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "disable the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
            "output_format": {
                "type": str,
                "default": "jpeg",
                "help": "output image format",
            },
        },
    },
    # Bytedance Seedream v4 text-to-image
    "seedream": {
        "endpoint": "fal-ai/bytedance/seedream/v4/text-to-image",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/bytedance/seedream/v4/text-to-image/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "image_size": {
                "type": "i",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3",
                                  "landscape_16_9", "auto", "auto_2K", "auto_4K", ],
                "flags": ["-i", "--image-size"],
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "disable the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
            "max_images": {
                "type": int,
                "default": None,
                "help": "maximum images allowed",
            },
        },
    },
    # Bytedance Seedream v4 edit (image editing with multiple reference images)
    "seedream-edit": {
        "endpoint": "fal-ai/bytedance/seedream/v4/edit",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/bytedance/seedream/v4/edit/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "image_size": {
                "type": "i",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3",
                                  "landscape_16_9", "auto", "auto_2K", "auto_4K", ],
                "flags": ["-i", "--image-size"],
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "disable the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
            "image_urls": {
                "type": str,
                "default": None,
                "help": "image URL input (repeatable)",
                "flags": ["--image-url", "--image-urls", "-u"],
                "action": "append",
                "metavar": "URL",
            },
        },
    },
    # qwen-image-edit (image editing with multiple reference images)
    "qwen-image-edit": {
        "endpoint": "fal-ai/qwen-image-edit-plus",
        "call": "subscribe",
        "doc_url": "https://fal.ai/models/fal-ai/qwen-image-edit-plus/api#schema",
        "options": {
            "prompt": {
                "type": "prompt",
                "default": None,
                "help": "prompt text",
                "file_help": "prompt file in prompts/",
            },
            "image_size": {
                "type": "whi",
                "default": "portrait_4_3",
                "help": "preset image size",
                "allowed_sizes": ["square_hd", "square", "portrait_4_3", "portrait_16_9", "landscape_4_3",
                                  "landscape_16_9", ],
                "flags": ["-i", "--image-size"],
            },
            "num_inference_steps": {
                "type": int,
                "default": 50,
                "help": "number of diffusion steps",
            },
            "guidance_scale": {
                "type": float,
                "default": 4.0,
                "help": "guidance scale",
            },
            "seed": {
                "type": int,
                "default": None,
                "help": "random seed (omit for random)",
                "flags": ["-s", "--seed"],
            },
            "num_images": {
                "type": int,
                "default": 1,
                "help": "number of images to generate",
                "flags": ["-#", "--num-images"],
            },
            "enable_safety_checker": {
                "type": bool,
                "default": False,
                "help": "enable the model safety checker",
                "disable_help": "disable the model safety checker",
                "flags": ["-%", "--enable-safety-checker"],
            },
            "output_format": {
                "type": str,
                "default": "jpeg",
                "help": "output image format (jpeg, png)",
            },
            "image_urls": {
                "type": str,
                "default": None,
                "help": "image URL input (repeatable)",
                "action": "append",
                "metavar": "URL",
                "flags": ["--image-url", "--image-urls", "-u"],
            },
            "negative_prompt": {
                "type": str,
                "default": "",
                "help": "negative prompt to steer away from unwanted details",
                "flags": ["-n", "--negative-prompt"],
            },
            "acceleration": {
                "type": str,
                "default": "regular",
                "help": "acceleration preset",
            },
        },
    },
}
